eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      defaultZone: http://service-discovery:8761/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true
jwt:
  secret_key: "secret"
